### ISSUE TITLE
Javascript error transfering file from JupyterLab

### ISSUE THREAD

**Issue by tmtabor** [globus/globus-jupyterlab#130] opened 2023-02-02 18:35 UTC
When I select a file in JupyterLab and attempt to transfer it to a remote Globus endpoint, it appears as if nothing happens. But when I open my Javascript console I see the following:

```
Uncaught (in promise) TypeError: b[0] is undefined
    onClick 909.9bf03a6db83e37f798af.js:1
    React 5
```

Jumping to that line ...

> ... a({response:{status:"DirectorySelectionError",statusText:"Please only select one remote directory to transfer data to"}});else if("file"==**b[0].type**)h(!1),a({response:{status:"DirectorySelectionError", ...

* **JupyterLab:** 3.4.7
* **globus_jupyterlab:** 1.0.0-beta.9

**Comment by NickolausDS** [comment] 2023-02-02 19:16
Thanks for creating a bug report!

Just to confirm, does this happen when no destination directory is selected?

**Comment by tmtabor** [comment] 2023-02-03 22:12
Yes, it seems to happen regardless of what is checked on the remote endpoint side.

**Comment by NickolausDS** [comment] 2023-02-03 23:11
Thanks for reporting. I think I was able to reproduce what looks like the problem on our test servers.

We've been busy with other projects, but should be able to have this fixed with a new release early next week.

**Comment by NickolausDS** [comment] 2023-02-07 20:57
@tmtabor This has been fixed and released in Beta 10. Users are still required to choose a directory for transfer, the app is responsive to the error and will direct the user to do so. I've added a backlog ticket (not sure when we'll have time to work on it!) for assuming the current directory if a destination isn't selected, which is what the webapp does and I think is a bit more intuitive.

Thanks for posting this error! Please reopen or create a new issue if you run into any more trouble.

**Closed by NickolausDS** 2023-02-07 20:57 UTC
Labels: bug
